# Generated by Django 5.0.1 on 2024-02-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("price", models.FloatField()),
                ("description", models.TextField()),
            ],
        ),
    ]
