# Generated by Django 5.0.1 on 2024-02-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nikeScraper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoes",
            name="category",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="shoes",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="shoes",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
